### ISSUE TITLE
Improve tables in report

### ISSUE THREAD

**Issue by milanwiedemann** [opensafely/pharmacy-first-data-development#51]
Following meeting 4th Nov we decided to imprve the tables with the following:
- Improve clarity of the tables
- Present data in table X as flowchart

**Comment by viv3ckj** [comment]
I had a think about this, not sure about if a flowchart would be appropriate as we're not really describing a process flow. Simple bar charts could have been helpful but all values are put into perspective due to 260 million all events, which makes all other values miniscule. 

I have looked into removing the pre section of the table, and perhaps would be better to switch the columns with the rows. Interested to see what you think.

**Comment by milanwiedemann** [comment]
we did this in various PRs, not exactly rethinking the entire presentation, but taking out some information that wasnt needed (pre data) and believe that this is now much better! if no one has other suggtions this is how we will presetnt the data for now
